services:
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile
    image: ticket-backend:latest
    restart: on-failure
    working_dir: /app
    ports:
      - "3123:3000"
      - "${WS_EXTERNAL_PORT:-3124}:${WS_PORT:-3001}"
    env_file:
      - .env
    environment:
      - NODE_ENV=production
      - DATABASE_URL=${DATABASE_URL}
    #    volumes:
    #      - ./src:/app/src:rw
    #      - ./package.json:/app/package.json:ro
    #      - ./tsconfig.json:/app/tsconfig.json:ro
    #      - node_modules:/app/node_modules
    command: ["bun", "src/index.ts"]

volumes:
  node_modules:
